### ISSUE TITLE
cd always prints destentation

### ISSUE THREAD

**Issue by nloomans** [lgutter/minishell#25]
According to the standard, cd should print the destination when using `cd -`:

> OPERANDS
> 
> The following operands shall be supported:
> 
> **directory**
> An absolute or relative pathname of the directory that shall become the new working directory. The interpretation of a relative pathname by cd depends on the -L option and the CDPATH and PWD environment variables. If directory is an empty string, the results are unspecified.
> **-**
> When a <hyphen-minus> is used as the operand, this shall be equivalent to the command:
> 
> `cd "$OLDPWD" && pwd`
> 
> which changes to the previous working directory and then writes its name.

The current implementation always prints the destination.

**Comment by lgutter** [comment]
This was deliberate to be more verbose, but i guess i'll follow the standard just to be sure.
